### ISSUE TITLE
2.7.2熔融交错钢无法浇筑交错锭导致卡进度

### ISSUE THREAD

**Issue by shirof1re** [Greediest-Studio/Greedycraft2#17]
B站查阅视频（来源：BV16KTge9EcB，3分38秒）发现高炉有用锭铸模直接浇筑交错钢的配方，但经查2.7.2没有锭铸模浇筑的配方也没有齿轮和板浇筑导致熔融交错钢无法通过任何途径转化为交错锭（无法直接浇筑锭，也无法浇筑为板和齿轮然后利用感应炉转化为锭）导致卡进度

**Comment by xbj2333** [comment]
已修复
