### ISSUE TITLE
271bug 

### ISSUE THREAD

**Issue by rabbit333333** [Greediest-Studio/Greedycraft2#6]
神秘奇境的元始加速器无法对撞出晶粒 这在260版本也有

**Comment by rabbit333333** [comment]
今晚等我回去再开创造档试试

**Comment by rabbit333333** [comment]
修复满混沌抗性混沌龙伤害过高的问题这个没修好吧 还是几下秒我

**Comment by EdwinYoungSteve** [comment]
> 修复满混沌抗性混沌龙伤害过高的问题这个没修好吧 还是几下秒我

之前特地把这个改难了，刀哥调的

**Comment by EdwinYoungSteve** [comment]
> 神秘奇境的元始加速器无法对撞出晶粒 这在260版本也有

不太像是bug，我这边正常？

**Comment by rabbit333333** [comment]
应该撞不出来 我记得有群友也和我一样

**Comment by rabbit333333** [comment]
> > 神秘奇境的元始加速器无法对撞出晶粒 这在260版本也有
> 
> 不太像是bug，我这边正常？

如果删除了神秘时代6修复（Thaumcraft Fix）这个模组就能出晶粒了

**Comment by EdwinYoungSteve** [comment]
已修复
