### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by yiyuan-gif** [Greediest-Studio/Greedycraft2#7]
极光幽境部分材料无法熔炼成液体，热力熔岩炉无法识别放入
![360截图20240823144055997](https://github.com/user-attachments/assets/83000b9f-cf9f-47df-ad03-02d2198a89da)
![360截图20240823144349157](https://github.com/user-attachments/assets/8b2640f7-f560-4750-98f4-0d9fe3e0ef57)

**Comment by rabbit333333** [comment]
什么版本的

**Comment by yiyuan-gif** [comment]
> What version
2.7.1

**Comment by rabbit333333** [comment]
我看着核电工艺里的熔化机能融粉、粒和块 就是不能融锭

**Comment by yiyuan-gif** [comment]
好吧，如果设计就是如此 。只是个人觉得要做耐钢，材料却在后面的既视感

**Comment by rabbit333333** [comment]
应该是bug

**Comment by yiyuan-gif** [comment]
> 应该是bug

好的你看是否能解决，之后我在仔细去体验后续内容。谢谢

**Comment by EdwinYoungSteve** [comment]
已经修复
